### ISSUE TITLE
Some Icons request

### ISSUE THREAD

**Issue by Simbiat** [viion/SaintCoinach#5]
This is not an issue, but rather a request. I am not that versatile at compiling C code, so, thought, maybe you can assist with me extracting some icons from game assets (will probably be a bit faster). I need icons used for Free Company permissions (5 in total: basic, chest, housing I, housing II, workshop) and a few quest icons: feature quest "completed", feature quest "completed" locked, lore quest "completed", main quest "completed". For quest icons http://zamarkand.com/wp-content/uploads/2017/09/Image-e1505129383632.png may give an idea of what I need.
Just for context: I need these icons to stylize company permissions in new version of my FFTracker. Current version ( http://simbiat.ru/fftracker/freecompany/9234631035923213559/all/ ) fullfills its purpose, but redesigned version I am working on needs a bit of a touch up and adding some graphics can work really well for it. I tried screencapturing permissions' icons but they are... Well.. I'd prefer slightly better quality.
Would really appreciate if you can assist me.

**Comment by Simbiat** [comment]
For reference, this is what I am doing: https://imgur.com/a/yEzot
As you can see, I have the icons, but they are somewhat rough along the edges and some of them are a bit pixalated. I am hoping to get cleaner icons of a bit higher resolution. If ranks icons (on the left side of the image) can be grabbed as well - that be even more awesome

**Comment by viion** [comment]
Go to the parent repo ufx and go to releases, download Cmd, rub it and type
help in the console

Thee is a command, I think called ui for all icons

**Comment by Simbiat** [comment]
It keeps telling me "Need data!" no matter what I try to pass to the .exe

**Comment by viion** [comment]
Try pass to the exe? Do you have FF in a non standard directory

**Comment by Simbiat** [comment]
Yes... In Steam's library. Do I need to move it to "C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn"?

**Comment by viion** [comment]
Might need to, if you have visual studio you could compile my version and
then run “setpath xxxxxx”

**Comment by Simbiat** [comment]
indeed, had to move the data. now it's extracting everything. hope, that what I need is in UI, indeed :D Thanks for help.

**Comment by Simbiat** [comment]
sadly, company permissions icons did not get extracted =( quest ones did, though.

**Comment by viion** [comment]
those icons are very unlikely to be part of an icon set and instead a uld set, which i dont think saint extracts,  probably better to just get them from lodestone as ulds are usually very low quality

**Comment by Simbiat** [comment]
Permissions were not published on the web before my post on Lodestone blog, so do not think permission icons are present on Lodestone. BTW, cities icons are bigger than those on Lodestone. Grand companies' ranks are smaller, though for some reason.

**Comment by viion** [comment]
https://github.com/viion/ffxiv-datamining/tree/master/uld

I have uploaded all uld icons here, you'll find GC rank icons in there, forgot number but they are part of an image with a bunch of little icons :) there some other juicy stuff in there you might like too

**Comment by Simbiat** [comment]
I meant not the rank icons (which lodestone parser does get), but "permissions" icons. Like "Housing", "Workshop". These icons are present, though, too: B6DEE5BB.png. They are lowscale, but seem a bit cleaner compared to what I captured. Thanks a bunch.
